# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expresslte or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/expresslte/proprietary/bin/netmgrd \
    vendor/samsung/expresslte/proprietary/bin/sec-ril \
    vendor/samsung/expresslte/proprietary/bin/qmiproxy \
    vendor/samsung/expresslte/proprietary/bin/qmuxd \
    vendor/samsung/expresslte/proprietary/bin/rild \
    vendor/samsung/expresslte/proprietary/bin/btnvtool \
    vendor/samsung/expresslte/proprietary/bin/hci_qcomm_init \
    vendor/samsung/expresslte/proprietary/bin/geomagneticd \
    vendor/samsung/expresslte/proprietary/bin/orientationd \
    vendor/samsung/expresslte/proprietary/bin/macloader \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.b00 \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.b01 \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.b02 \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.b04 \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.b05 \
    vendor/samsung/expresslte/proprietary/etc/firmware/wcnss.mdt \
    vendor/samsung/expresslte/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/samsung/expresslte/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/samsung/expresslte/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/samsung/expresslte/proprietary/lib/libaudcal.so \
    vendor/samsung/expresslte/proprietary/lib/libaudioalsa.so \
    vendor/samsung/expresslte/proprietary/lib/libcsd-client.so \
    vendor/samsung/expresslte/proprietary/lib/libril-qc-qmi-1.so \
    vendor/samsung/expresslte/proprietary/lib/libril.so \
    vendor/samsung/expresslte/proprietary/lib/libsecril-client.so \
    vendor/samsung/expresslte/proprietary/lib/libqmi.so \
    vendor/samsung/expresslte/proprietary/lib/libqdi.so \
    vendor/samsung/expresslte/proprietary/lib/libqdp.so \
    vendor/samsung/expresslte/proprietary/lib/libqmiservices.so \
    vendor/samsung/expresslte/proprietary/lib/libreference-ril.so \
    vendor/samsung/expresslte/proprietary/lib/libdsi_netctrl.so \
    vendor/samsung/expresslte/proprietary/lib/libnetmgr.so \
    vendor/samsung/expresslte/proprietary/lib/libqmi_cci.so \
    vendor/samsung/expresslte/proprietary/lib/libqmi_csi.so \
    vendor/samsung/expresslte/proprietary/lib/libqcci_legacy.so \
    vendor/samsung/expresslte/proprietary/lib/libqmi_client_qmux.so \
    vendor/samsung/expresslte/proprietary/lib/libomission_avoidance.so \
    vendor/samsung/expresslte/proprietary/lib/libfactoryutil.so \
    vendor/samsung/expresslte/proprietary/lib/hw/nfc.MSM8960.so \
    vendor/samsung/expresslte/proprietary/lib/hw/camera.msm8960.so \
    vendor/samsung/expresslte/proprietary/lib/libmmjpeg.so \
    vendor/samsung/expresslte/proprietary/lib/libmmstillomx.so \
    vendor/samsung/expresslte/proprietary/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/expresslte/proprietary/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/expresslte/proprietary/lib/libimage-omx-common.so \
    vendor/samsung/expresslte/proprietary/lib/libgemini.so \
    vendor/samsung/expresslte/proprietary/lib/liboemcamera.so \
    vendor/samsung/expresslte/proprietary/lib/libmmcamera_frameproc.so \
    vendor/samsung/expresslte/proprietary/lib/libmmcamera_statsproc31.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_imx074_preview.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/expresslte/proprietary/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/expresslte/proprietary/lib/hw/sensors.msm8960.so \
    vendor/samsung/expresslte/proprietary/lib/libsensor_yamaha532_test.so \
    vendor/samsung/expresslte/proprietary/lib/libdiag.so \
    vendor/samsung/expresslte/proprietary/vendor/firmware/libpn547_fw.so \
    vendor/samsung/expresslte/proprietary/vendor/firmware/libpn547_fw_eng.so \
    vendor/samsung/expresslte/proprietary/vendor/firmware/libpn547_fw_platform.so \
